#!/bin/bash

mkdir battery extra images extra/audio extra/clock extra/scripts images/icon

wget https://archivethingmacosamfi.vercel.app/desk7/battery/script.js -O battery/script.js
wget https://archivethingmacosamfi.vercel.app/desk7/battery/script2.js -O battery/script2.js
wget https://archivethingmacosamfi.vercel.app/desk7/extra/chat.html -O extra/chat.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/chatalt.html -O extra/chatalt.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/error.png -O extra/error.png
wget https://archivethingmacosamfi.vercel.app/desk7/extra/google.html -O extra/google.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/privacyerror.html -O extra/privacyerror.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/sitecrashes.html -O extra/sitecrashes.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/smallprivacyerror.html -O extra/smallprivacyerror.html
wget https://archivethingmacosamfi.vercel.app/desk7/extra/wr4.JPG -O extra/wr4.JPG
wget https://archivethingmacosamfi.vercel.app/desk7/extra/audio/alert.mp3 -O extra/audio/alert.mp3
wget https://archivethingmacosamfi.vercel.app/desk7/extra/audio/lock.mp3 -O extra/audio/lock.mp3
wget https://archivethingmacosamfi.vercel.app/desk7/extra/clock/clock.css -O extra/clock/clock.css
wget https://archivethingmacosamfi.vercel.app/desk7/extra/clock/clock.js -O extra/clock/clock.js
wget https://archivethingmacosamfi.vercel.app/desk7/extra/scripts/accent.js -O extra/scripts/accent.js
wget https://archivethingmacosamfi.vercel.app/desk7/extra/scripts/wallpaper.js -O extra/scripts/wallpaper.js
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/about.png -O images/icon/about.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/apps.png -O images/icon/apps.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/context.png -O images/icon/context.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/deves.jpg -O images/icon/deeves.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/deskcal.png -O images/icon/deskcal.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/deskcalc.png -O images/icon/deskcalc.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/downarrow.png -O images/icon/downarrow.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/error.png -O images/icon/error.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/favicon.jpg -O images/icon/favicon.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/fullscreen.png -O images/icon/fullscreen.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/googlewhite.png -O images/icon/googlewhite.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/IMG_1110.png -O images/icon/IMG_1110.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/lock.png -O images/icon/lock.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/maps.png -O images/icon/maps.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/menu.png -O images/icon/menu.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/migration.png -O images/icon/migration.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/mine.png -O images/icon/mine.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/pref.png -O images/icon/pref.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/scriptmod.png -O images/icon/scriptmod.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/search.png -O images/icon/search.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/setup.png -O images/icon/setup.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/snake.png -O images/icon/snake.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/text.png -O images/icon/text.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/textedit.png -O images/icon/textedit.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/icon/viewer.png -O images/icon/viewer.png
wget https://archivethingmacosamfi.vercel.app/desk7/images/404.jpg -O images/404.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr1.jpg -O images/wr1.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr2.jpg -O images/wr2.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr3.jpg -O images/wr3.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr4.jpg -O images/wr4.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr5.jpg -O images/wr5.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr7.jpg -O images/wr6.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr8.jpg -O images/wr7.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr8.jpg -O images/wr8.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr9.jpg -O images/wr9.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr10.jpg -O images/wr10.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/wr11.jpg -O images/wr11.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/images/404.jpg -O images/404.jpg
wget https://archivethingmacosamfi.vercel.app/desk7/404.html -O 404.html
